
export const TOGGLE_MENU = "TOGGLE_MENU"

//github

//user
export const GET_GITHUBUSER_INFO_REQUEST = "GET_GITHUBUSER_INFO_REQUEST"
export const GET_GITHUBUSER_INFO_SUCCESS = "GET_GITHUBUSER_INFO_SUCCESS"
export const GET_GITHUBUSER_INFO_FAIL = "GET_GITHUBUSER_INFO_FAIL"

//org
export const GET_GITHUBORG_INFO_REQUEST = "GET_GITHUBORG_INFO_REQUEST"
export const GET_GITHUBORG_INFO_SUCCESS = "GET_GITHUBORG_INFO_SUCCESS"
export const GET_GITHUBORG_INFO_FAIL = "GET_GITHUBORG_INFO_FAIL"







